# Generated by Django 6.0.2 on 2026-02-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
