# Generated by Django 6.0.2 on 2026-02-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
