# Generated by Django 6.0.2 on 2026-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluida_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='situacao',
            field=models.BooleanField(default=False),
        ),
    ]
